### ISSUE TITLE
根据你的配置信息走下来,到最后打包出来的并不是rem啊

### ISSUE THREAD

**Issue by yyuxiang** [CallMeXYZ/px2rem#1]
根据你的配置信息走下来,到最后打包出来的并不是rem啊,求知若渴

**Comment by CodePlayer7** [comment]
看下你的`webpack.config.js`

**Comment by yyuxiang** [comment]
![image](https://user-images.githubusercontent.com/24794439/29447700-acc72498-8425-11e7-826a-e392e7d15095.png)

**Comment by yyuxiang** [comment]
是不是我贴配置的位置不对啊?~~~￣へ￣

**Comment by CodePlayer7** [comment]
等下 我知道了 我忙完这会告诉你哈

**Comment by yyuxiang** [comment]
想转换vue文件里面的css的~ 对这些配置不太熟悉 能具体说下哪些loader没写吗?

**Comment by yyuxiang** [comment]
好的~谢谢啦~~

**Comment by CodePlayer7** [comment]
`webpack`现在用`rules`替代以前的`loaders`，所以你把那段配置加到`rules`里就行了，不用再配置`loaders`

**Comment by yyuxiang** [comment]
嗯呐~我现在改一下~~请问其他的地方还有要改的吗?

**Comment by CodePlayer7** [comment]
不用了

**Comment by yyuxiang** [comment]
嗯嗯,我现在试一下,谢谢XYZ

**Comment by CodePlayer7** [comment]
哈哈没啥，这个是一年前我需要这个功能时自己做的，后面没啥新需求就没更新了，看来我以后得丰富一下。你也可以看看别的高star的项目，功能都很丰富啊

**Comment by yyuxiang** [comment]
嗯呐,最好是打包好的css贴出来一下,虽然根据配置信息一路下来,但是没有一个模板比划着,怎么感觉自己都是不对的.别的项目我也在看啦,尽可能的多几种方法,方便收藏啦哈O(∩_∩)O哈哈~

**Comment by CodePlayer7** [comment]
例子里面就是啊，如果`loader`配置正确，那么所有的`px`都为转化为`rem`，你在页面上看原先的单位变化没就可以确定成功与否了。

**Comment by yyuxiang** [comment]
嗯嗯  今天谢谢你啦哈

**Comment by CodePlayer7** [comment]
没啥 一起进步
